version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: survey
    versions:
    - ">= 3.a, < 4"
  - dependency-name: watchdog
    versions:
    - 2.0.0
