repos:
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
    -   id: mypy
        additional_dependencies:
            - "types-setuptools"
            - "types-requests"

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
