repos:
-   repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
    - id: black
      language_version: python3

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.920
    hooks:
    -   id: mypy
        additional_dependencies:
            - "types-setuptools"
            - "types-requests"

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
